#!/bin/sh
if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <spec_number> [cxxflags_extra]"
  exit 1
fi

spec_number=$1
cxxflags_extra="-static -std=c++11 -O3 "
if [ "$#" -ge 2 ]; then
  cxxflags_extra+=$2
fi

# 0. clean
make clean

# 1. Generate transformer.cpp before rebuild
spec_file="./tests/${spec_number}_spec.json"
# ./scripts/auto_gen_transformer --input ./tests/00_spec.json --output transformer.cpp
# ./scripts/auto_gen_transformer --input ./tests/01_spec.json --output transformer.cpp
./scripts/auto_gen_transformer --input "$spec_file" --output transformer.cpp

# 2. Build
scl enable devtoolset-8 "make CXXFLAGS='${cxxflags_extra}'"